// BSB audio Bible chapter player, with per-verse follow-along.
//
// Playback is the real Faith Comes By Hearing BSB recording streamed from R2
// with Range support, so the native <audio> controls can seek.
//
// Per-verse sync comes from timing data generated by forced alignment (see
// tools/ and the alignment workflow), served per-book from
// /data/bsb-timings/<Book>.json. A book with no timings yet simply plays
// without follow-along rather than erroring.
//
// Worth being precise about the OT caveat, because it is narrower than it
// first looks: the app's OT text is JPS 1917 while the audio is BSB, so the
// WORDING differs — but both use the same verse divisions, so verse
// boundaries still line up and highlighting verse 5 while verse 5 is read is
// correct in both testaments. Only word-level highlighting would be wrong for
// the OT, and that is not what this does.
(function () {
  var MANIFEST_URL = (window.SWRV_API_BASE || '') + '/data/bsb-audio-manifest.json';
  var TIMINGS_BASE = (window.SWRV_API_BASE || '') + '/data/bsb-timings/';
  var FOLLOW_KEY = 'swrv_audio_follow';
  var manifest = null;
  var manifestState = 'idle'; // idle | loading | ready | unavailable
  var lastKey = null; // "Book:chapter" of what the player is currently showing
  var timings = {};        // Book -> {chapters:{ch:[[begin,end],...]}} | 'unavailable'
  var activeSpans = null;  // [{n, begin, end, el}] for the chapter on screen
  var activeVerseN = null;
  var follow = true;
  try { follow = localStorage.getItem(FOLLOW_KEY) !== '0'; } catch (e) {}

  function bar()   { return document.getElementById('audioBibleBar'); }
  function audioEl(){ return document.getElementById('audioBibleEl'); }
  function noteEl(){ return document.getElementById('audioBibleInfo'); }

  function loadManifest(cb) {
    if (manifestState === 'ready' || manifestState === 'unavailable') { cb(); return; }
    if (manifestState === 'loading') {
      // Another call is already in flight — check back shortly rather than
      // firing a second fetch.
      setTimeout(function () { loadManifest(cb); }, 150);
      return;
    }
    manifestState = 'loading';
    fetch(MANIFEST_URL).then(function (res) {
      if (!res.ok) throw new Error('manifest not available (status ' + res.status + ')');
      return res.json();
    }).then(function (data) {
      manifest = data;
      manifestState = 'ready';
      cb();
    }).catch(function () {
      manifest = null;
      manifestState = 'unavailable';
      cb();
    });
  }

  function refresh() {
    var book = window.currentBook, ch = window.currentChapter;
    if (!book || !ch) { hide(); return; }
    var key = book + ':' + ch;
    if (key === lastKey) return; // already showing this chapter (or already hidden for it)
    lastKey = key;

    loadManifest(function () {
      if (!manifest || !manifest.books) { hide(); return; }
      var entry = manifest.books[book];
      var r2Key = entry && entry.chapters && entry.chapters[ch];
      if (!r2Key) { hide(); return; }
      show(entry.testament, r2Key);
    });
  }

  // ---- per-verse timings -------------------------------------------------
  function loadTimings(book, cb) {
    if (timings[book] === 'unavailable') { cb(null); return; }
    if (timings[book] === 'loading') { setTimeout(function () { loadTimings(book, cb); }, 150); return; }
    if (timings[book]) { cb(timings[book]); return; }
    timings[book] = 'loading';
    fetch(TIMINGS_BASE + encodeURIComponent(book) + '.json').then(function (res) {
      if (!res.ok) throw new Error('no timings');
      return res.json();
    }).then(function (data) {
      timings[book] = data;
      cb(data);
    }).catch(function () {
      // A book without alignment data is a normal state, not an error —
      // playback still works, just without follow-along.
      timings[book] = 'unavailable';
      cb(null);
    });
  }

  // Verse elements are found by scanning the rendered chapter and reading
  // each verse's number, NOT by reconstructing element ids from the book
  // key. The ids come from refs like "1 Samuel 1:1" -> "1_Samuel_1_1",
  // while the book key is "1Samuel" — so id reconstruction silently missed
  // every numbered book (1/2 Samuel, Kings, Chronicles, Corinthians, ...)
  // and Song of Solomon. Genesis matched by luck, which is why the bug
  // wasn't obvious. Scanning the DOM is format-proof.
  function verseElementMap() {
    var map = {};
    var els = document.querySelectorAll('.verse');
    for (var i = 0; i < els.length; i++) {
      var numEl = els[i].querySelector('.verse-num');
      var n = numEl ? parseInt(numEl.textContent, 10) : NaN;
      if (!isNaN(n) && !map[n]) map[n] = els[i];
    }
    return map;
  }

  function buildSpans(book, ch) {
    activeSpans = null;
    activeVerseN = null;
    loadTimings(book, function (data) {
      if (!data || !data.chapters) return;
      var rows = data.chapters[String(ch)];
      if (!rows || !rows.length) return;
      var els = verseElementMap();
      var spans = [];
      for (var i = 0; i < rows.length; i++) {
        var n = i + 1; // rows are verse-ordered, index 0 == verse 1
        spans.push({ n: n, begin: Number(rows[i][0]), end: Number(rows[i][1]), el: els[n] || null });
      }
      activeSpans = spans;
    });
  }

  // Binary search rather than a linear scan: timeupdate fires several times a
  // second and Psalm 119 alone is 176 verses.
  function verseAt(t) {
    if (!activeSpans || !activeSpans.length) return null;
    var lo = 0, hi = activeSpans.length - 1, best = null;
    while (lo <= hi) {
      var mid = (lo + hi) >> 1;
      var s = activeSpans[mid];
      if (t < s.begin) { hi = mid - 1; }
      else if (t >= s.end) { lo = mid + 1; best = s; }
      else { return s; }
    }
    return best;
  }

  function clearHighlight() {
    var prev = document.querySelector('.verse.verse-audio-active');
    if (prev) prev.classList.remove('verse-audio-active');
  }

  function onTimeUpdate() {
    var a = audioEl();
    if (!a || !activeSpans) return;
    var s = verseAt(a.currentTime);
    if (!s || s.n === activeVerseN) return;
    activeVerseN = s.n;
    clearHighlight();
    // Elements are re-rendered on navigation and mode switches, so
    // re-resolve lazily (same DOM scan as buildSpans) rather than trusting
    // the reference captured at build time.
    if (!s.el || !s.el.isConnected) {
      var els = verseElementMap();
      for (var i = 0; i < activeSpans.length; i++) {
        activeSpans[i].el = els[activeSpans[i].n] || null;
      }
    }
    if (!s.el) return;
    s.el.classList.add('verse-audio-active');
    if (follow && !a.paused) {
      var r = s.el.getBoundingClientRect();
      if (r.top < 90 || r.bottom > window.innerHeight - 90) {
        s.el.scrollIntoView({ block: 'center', behavior: 'smooth' });
      }
    }
  }

  // Tap a verse number to jump the audio to that verse.
  document.addEventListener('click', function (e) {
    if (!activeSpans) return;
    var num = e.target.closest && e.target.closest('.verse-num');
    if (!num) return;
    var verseEl = num.closest('.verse');
    if (!verseEl || !verseEl.id) return;
    var m = /_(\d+)$/.exec(verseEl.id);
    if (!m) return;
    var s = activeSpans[Number(m[1]) - 1];
    var a = audioEl();
    if (!s || !a || !a.src) return;
    a.currentTime = s.begin;
    if (a.paused) a.play().catch(function () {});
  });

  window._audioToggleFollow = function (btn) {
    follow = !follow;
    try { localStorage.setItem(FOLLOW_KEY, follow ? '1' : '0'); } catch (e) {}
    if (btn) btn.setAttribute('aria-pressed', follow ? 'true' : 'false');
  };

  function show(testament, r2Key) {
    var b = bar();
    var a = audioEl();
    if (!b || !a) return;
    var src = (window.SWRV_API_BASE || '') + '/api/audio-bible/' + r2Key.split('/').map(encodeURIComponent).join('/');
    if (a.getAttribute('data-src') !== src) {
      a.pause();
      a.src = src;
      a.setAttribute('data-src', src);
      clearHighlight();
    }
    if (!a.getAttribute('data-sync-bound')) {
      a.setAttribute('data-sync-bound', '1');
      a.addEventListener('timeupdate', onTimeUpdate);
      a.addEventListener('seeked', onTimeUpdate);
      a.addEventListener('pause', function () { document.body.classList.remove('audio-bible-playing'); });
      a.addEventListener('play', function () { document.body.classList.add('audio-bible-playing'); });
    }
    document.body.classList.add('audio-bible-active');
    buildSpans(window.currentBook, window.currentChapter);
    // The OT/NT wording-match text used to render as a visible span in the
    // bar — removed per explicit request (it was in the way). The "i" icon
    // always shows; only its tooltip changes, so the information survives
    // without taking up bar space.
    var n = noteEl();
    if (n) {
      // Per-verse timings exist for BOTH testaments (JPS and BSB share verse
      // divisions even where wording differs), so the verse being read
      // highlights everywhere — the OT note is only about wording.
      n.title = testament === 'OT'
        ? 'This app’s Old Testament text is the 1917 JPS translation; this audio is the Berean Standard Bible (BSB). The verse being read still highlights — but the spoken words won’t match the on-screen words exactly.'
        : 'This app’s New Testament text is also the Berean Standard Bible (BSB), so this audio matches the on-screen wording word-for-word.';
    }
    b.style.display = '';
  }

  function hide() {
    var b = bar();
    if (b) b.style.display = 'none';
    var a = audioEl();
    if (a && a.src) { a.pause(); }
    document.body.classList.remove('audio-bible-active');
    clearHighlight();
    activeSpans = null;
    activeVerseN = null;
  }

  // No chapter-change event exists to hook (checked: app.js dispatches none
  // for navigation), and wiring this into every navigation call site
  // (loadBook/loadChapter/nextChapter/prevChapter/goToVerse/...) would be
  // invasive across a large, unfamiliar codebase. A light poll comparing
  // window.currentBook/currentChapter is simple, can't desync, and costs
  // nothing noticeable at this interval.
  setInterval(refresh, 400);

  if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', refresh);
  } else {
    refresh();
  }
})();
