// BSB audio Bible chapter player, with per-verse follow-along.
//
// Playback is the real Faith Comes By Hearing BSB recording streamed from R2
// with Range support, so the native <audio> controls can seek.
//
// Per-verse sync comes from timing data generated by forced alignment (see
// tools/ and the alignment workflow), served per-book from
// /data/bsb-timings/<Book>.json. A book with no timings yet simply plays
// without follow-along rather than erroring.
//
// Worth being precise about the OT caveat, because it is narrower than it
// first looks: the app's OT text is JPS 1917 while the audio is BSB, so the
// WORDING differs — but both use the same verse divisions, so verse
// boundaries still line up and highlighting verse 5 while verse 5 is read is
// correct in both testaments. Only word-level highlighting would be wrong for
// the OT, and that is not what this does.
(function () {
  var MANIFEST_URL = (window.SWRV_API_BASE || '') + '/data/bsb-audio-manifest.json';
  var TIMINGS_BASE = (window.SWRV_API_BASE || '') + '/data/bsb-timings/';
  var FOLLOW_KEY = 'swrv_audio_follow';
  var manifest = null;
  var manifestState = 'idle'; // idle | loading | ready | unavailable
  var lastKey = null; // "Book:chapter" of what the player is currently showing
  var timings = {};        // Book -> {chapters:{ch:[[begin,end],...]}} | 'unavailable'
  var activeSpans = null;  // [{n, begin, end, el}] for the chapter on screen
  var activeVerseN = null;
  var follow = true;
  try { follow = localStorage.getItem(FOLLOW_KEY) !== '0'; } catch (e) {}
  var CONTINUOUS_KEY = 'swrv_audio_continuous';
  var continuous = true;
  try { continuous = localStorage.getItem(CONTINUOUS_KEY) !== '0'; } catch (e) {}
  // Set right before calling nextChapter() so the next show() call (async,
  // triggered by the refresh() poll once the new chapter's data has loaded)
  // knows to resume playback instead of just cueing it up silently.
  var resumeOnLoad = false;
  // Repeat-this-verse: deliberately NOT persisted across page loads (unlike
  // follow/continuous, which are steady-state preferences) — this is a
  // "loop what I'm hearing right now" action, tied to one specific verse in
  // one specific chapter, so it always starts off and resets whenever the
  // chapter changes (see buildSpans below).
  var repeatVerse = false;
  var repeatTargetN = null; // verse number currently being looped, or null

  function bar()   { return document.getElementById('audioBibleBar'); }
  function audioEl(){ return document.getElementById('audioBibleEl'); }
  function noteEl(){ return document.getElementById('audioBibleInfo'); }

  function loadManifest(cb) {
    if (manifestState === 'ready' || manifestState === 'unavailable') { cb(); return; }
    if (manifestState === 'loading') {
      // Another call is already in flight — check back shortly rather than
      // firing a second fetch.
      setTimeout(function () { loadManifest(cb); }, 150);
      return;
    }
    manifestState = 'loading';
    fetch(MANIFEST_URL).then(function (res) {
      if (!res.ok) throw new Error('manifest not available (status ' + res.status + ')');
      return res.json();
    }).then(function (data) {
      manifest = data;
      manifestState = 'ready';
      cb();
    }).catch(function () {
      manifest = null;
      manifestState = 'unavailable';
      cb();
    });
  }

  function refresh() {
    var book = window.currentBook, ch = window.currentChapter;
    if (!book || !ch) { hide(); return; }
    var key = book + ':' + ch;
    if (key === lastKey) return; // already showing this chapter (or already hidden for it)
    lastKey = key;

    loadManifest(function () {
      if (!manifest || !manifest.books) { hide(); return; }
      var entry = manifest.books[book];
      var r2Key = entry && entry.chapters && entry.chapters[ch];
      if (!r2Key) { hide(); return; }
      show(entry.testament, r2Key);
    });
  }

  // ---- per-verse timings -------------------------------------------------
  function loadTimings(book, cb) {
    if (timings[book] === 'unavailable') { cb(null); return; }
    if (timings[book] === 'loading') { setTimeout(function () { loadTimings(book, cb); }, 150); return; }
    if (timings[book]) { cb(timings[book]); return; }
    timings[book] = 'loading';
    fetch(TIMINGS_BASE + encodeURIComponent(book) + '.json').then(function (res) {
      if (!res.ok) throw new Error('no timings');
      return res.json();
    }).then(function (data) {
      timings[book] = data;
      cb(data);
    }).catch(function () {
      // A book without alignment data is a normal state, not an error —
      // playback still works, just without follow-along.
      timings[book] = 'unavailable';
      cb(null);
    });
  }

  // Verse elements are found by scanning the rendered chapter and reading
  // each verse's number, NOT by reconstructing element ids from the book
  // key. The ids come from refs like "1 Samuel 1:1" -> "1_Samuel_1_1",
  // while the book key is "1Samuel" — so id reconstruction silently missed
  // every numbered book (1/2 Samuel, Kings, Chronicles, Corinthians, ...)
  // and Song of Solomon. Genesis matched by luck, which is why the bug
  // wasn't obvious. Scanning the DOM is format-proof.
  function verseElementMap() {
    var map = {};
    var els = document.querySelectorAll('.verse');
    for (var i = 0; i < els.length; i++) {
      var numEl = els[i].querySelector('.verse-num');
      var n = numEl ? parseInt(numEl.textContent, 10) : NaN;
      if (!isNaN(n) && !map[n]) map[n] = els[i];
    }
    return map;
  }

  function buildSpans(book, ch) {
    activeSpans = null;
    activeVerseN = null;
    // A new chapter invalidates any active repeat-loop — repeating verse 3
    // of the chapter someone just left doesn't carry over to the next one.
    if (repeatVerse) {
      repeatVerse = false;
      repeatTargetN = null;
      var rbtn = document.getElementById('audioRepeatToggle');
      if (rbtn) rbtn.setAttribute('aria-pressed', 'false');
    }
    loadTimings(book, function (data) {
      if (!data || !data.chapters) return;
      var rows = data.chapters[String(ch)];
      if (!rows || !rows.length) return;
      var els = verseElementMap();
      var spans = [];
      for (var i = 0; i < rows.length; i++) {
        var row = rows[i];
        // New format carries the real verse number explicitly (see
        // tools/align-book.mjs) — a chapter with a BSB-omitted verse (Mark
        // 9:44/46, Acts 8:37, etc.) has a gap in its rows, so "row i is verse
        // i+1" is only safe for the legacy positional [begin,end] format
        // still live for books not yet regenerated.
        var n = Array.isArray(row) ? i + 1 : row.n;
        var begin = Array.isArray(row) ? row[0] : row.begin;
        var end = Array.isArray(row) ? row[1] : row.end;
        spans.push({ n: n, begin: Number(begin), end: Number(end), el: els[n] || null });
      }
      activeSpans = spans;
    });
  }

  // Binary search rather than a linear scan: timeupdate fires several times a
  // second and Psalm 119 alone is 176 verses.
  function verseAt(t) {
    if (!activeSpans || !activeSpans.length) return null;
    var lo = 0, hi = activeSpans.length - 1, best = null;
    while (lo <= hi) {
      var mid = (lo + hi) >> 1;
      var s = activeSpans[mid];
      if (t < s.begin) { hi = mid - 1; }
      else if (t >= s.end) { lo = mid + 1; best = s; }
      else { return s; }
    }
    return best;
  }

  function clearHighlight() {
    var prev = document.querySelector('.verse.verse-audio-active');
    if (prev) prev.classList.remove('verse-audio-active');
  }

  function onTimeUpdate() {
    var a = audioEl();
    if (!a || !activeSpans) return;
    // Repeat-this-verse: as soon as playback nears the end of the locked
    // verse, jump back to its start instead of letting it roll into the
    // next verse (or, for the chapter's last verse, into 'ended' and
    // continuous-playback advancing to the next chapter — repeat always
    // wins over continuous while it's active). A small lead (0.08s) so the
    // loop-back fires before the boundary rather than a frame after it.
    if (repeatVerse && repeatTargetN != null) {
      var target = activeSpans[repeatTargetN - 1];
      if (target && a.currentTime >= target.end - 0.08) {
        a.currentTime = target.begin;
        return;
      }
    }
    var s = verseAt(a.currentTime);
    if (!s) return;
    // Repeat was just turned on with nothing/nowhere locked yet (e.g.
    // engaged the moment playback started) — lock onto whatever verse is
    // actually playing right now.
    if (repeatVerse && repeatTargetN == null) repeatTargetN = s.n;
    if (s.n === activeVerseN) return;
    activeVerseN = s.n;
    clearHighlight();
    // Elements are re-rendered on navigation and mode switches, so
    // re-resolve lazily (same DOM scan as buildSpans) rather than trusting
    // the reference captured at build time.
    if (!s.el || !s.el.isConnected) {
      var els = verseElementMap();
      for (var i = 0; i < activeSpans.length; i++) {
        activeSpans[i].el = els[activeSpans[i].n] || null;
      }
    }
    if (!s.el) return;
    s.el.classList.add('verse-audio-active');
    if (follow && !a.paused) {
      var r = s.el.getBoundingClientRect();
      if (r.top < 90 || r.bottom > window.innerHeight - 90) {
        s.el.scrollIntoView({ block: 'center', behavior: 'smooth' });
      }
    }
  }

  // Tap a verse number to jump the audio to that verse.
  document.addEventListener('click', function (e) {
    if (!activeSpans) return;
    var num = e.target.closest && e.target.closest('.verse-num');
    if (!num) return;
    var verseEl = num.closest('.verse');
    if (!verseEl || !verseEl.id) return;
    var m = /_(\d+)$/.exec(verseEl.id);
    if (!m) return;
    var s = activeSpans[Number(m[1]) - 1];
    var a = audioEl();
    if (!s || !a || !a.src) return;
    a.currentTime = s.begin;
    // Tapping a verse while repeat is on switches the loop to that verse —
    // "whichever verse is on" should always be the one that repeats.
    if (repeatVerse) repeatTargetN = s.n;
    if (a.paused) a.play().catch(function () {});
  });

  window._audioToggleFollow = function (btn) {
    follow = !follow;
    try { localStorage.setItem(FOLLOW_KEY, follow ? '1' : '0'); } catch (e) {}
    if (btn) btn.setAttribute('aria-pressed', follow ? 'true' : 'false');
  };

  window._audioToggleContinuous = function (btn) {
    continuous = !continuous;
    try { localStorage.setItem(CONTINUOUS_KEY, continuous ? '1' : '0'); } catch (e) {}
    if (btn) {
      btn.setAttribute('aria-pressed', continuous ? 'true' : 'false');
      btn.style.opacity = continuous ? '' : '0.45';
    }
  };

  window._audioToggleRepeatVerse = function (btn) {
    repeatVerse = !repeatVerse;
    // Lock onto whatever verse is currently playing/highlighted the moment
    // repeat is turned on; cleared when turned off so it starts fresh next time.
    repeatTargetN = repeatVerse ? activeVerseN : null;
    if (btn) btn.setAttribute('aria-pressed', repeatVerse ? 'true' : 'false');
  };

  function show(testament, r2Key) {
    var b = bar();
    var a = audioEl();
    if (!b || !a) return;
    var src = (window.SWRV_API_BASE || '') + '/api/audio-bible/' + r2Key.split('/').map(encodeURIComponent).join('/');
    if (a.getAttribute('data-src') !== src) {
      a.pause();
      a.src = src;
      a.setAttribute('data-src', src);
      clearHighlight();
    }
    if (!a.getAttribute('data-sync-bound')) {
      a.setAttribute('data-sync-bound', '1');
      a.addEventListener('timeupdate', onTimeUpdate);
      a.addEventListener('seeked', onTimeUpdate);
      a.addEventListener('pause', function () { document.body.classList.remove('audio-bible-playing'); });
      a.addEventListener('play', function () { document.body.classList.add('audio-bible-playing'); });
      // Continuous playback: when a chapter finishes, move on to the next
      // one and keep going — so listening doesn't require babysitting the
      // player after every chapter. nextChapter() already rolls over into
      // the next book at a book's last chapter. If there's no more audio
      // (manifest has no entry for the new chapter), show()/hide() below
      // just won't resume anything, which is the correct stop condition.
      a.addEventListener('ended', function () {
        if (!continuous) return;
        if (typeof window.nextChapter !== 'function') return;
        resumeOnLoad = true;
        window.nextChapter();
      });
    }
    if (resumeOnLoad) {
      resumeOnLoad = false;
      a.play().catch(function () {});
    }
    document.body.classList.add('audio-bible-active');
    buildSpans(window.currentBook, window.currentChapter);
    // The OT/NT wording-match text used to render as a visible span in the
    // bar — removed per explicit request (it was in the way). The "i" icon
    // always shows; only its tooltip changes, so the information survives
    // without taking up bar space.
    var n = noteEl();
    if (n) {
      // Per-verse timings exist for BOTH testaments (JPS and BSB share verse
      // divisions even where wording differs), so the verse being read
      // highlights everywhere — the OT note is only about wording.
      n.title = testament === 'OT'
        ? 'This app’s Old Testament text is the 1917 JPS translation; this audio is the Berean Standard Bible (BSB). The verse being read still highlights — but the spoken words won’t match the on-screen words exactly.'
        : 'This app’s New Testament text is also the Berean Standard Bible (BSB), so this audio matches the on-screen wording word-for-word.';
    }
    b.style.display = '';
  }

  function hide() {
    var b = bar();
    if (b) b.style.display = 'none';
    var a = audioEl();
    if (a && a.src) { a.pause(); }
    document.body.classList.remove('audio-bible-active');
    clearHighlight();
    activeSpans = null;
    activeVerseN = null;
    // The chapter we landed on (e.g. after continuous playback rolled past
    // the end of the last book with audio) has nothing to play — don't let
    // a stale resume request fire on some unrelated later navigation.
    resumeOnLoad = false;
  }

  // No chapter-change event exists to hook (checked: app.js dispatches none
  // for navigation), and wiring this into every navigation call site
  // (loadBook/loadChapter/nextChapter/prevChapter/goToVerse/...) would be
  // invasive across a large, unfamiliar codebase. A light poll comparing
  // window.currentBook/currentChapter is simple, can't desync, and costs
  // nothing noticeable at this interval.
  setInterval(refresh, 400);

  function initButtonStates() {
    var cbtn = document.getElementById('audioContinuousToggle');
    if (cbtn) {
      cbtn.setAttribute('aria-pressed', continuous ? 'true' : 'false');
      cbtn.style.opacity = continuous ? '' : '0.45';
    }
    var fbtn = document.getElementById('audioFollowToggle');
    if (fbtn) fbtn.setAttribute('aria-pressed', follow ? 'true' : 'false');
    var rbtn = document.getElementById('audioRepeatToggle');
    if (rbtn) rbtn.setAttribute('aria-pressed', repeatVerse ? 'true' : 'false');
  }

  if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', function () { refresh(); initButtonStates(); });
  } else {
    refresh();
    initButtonStates();
  }
})();
